# Site settings

firebaseApiKey:             "AIzaSyCftcr4mEfhCgj2b0_0fr-2G-DLHuENIm0"
firebaseAuthDomain:         "fiery-inferno-2998.firebaseapp.com"
firebaseDatabaseURL:        "https://fiery-inferno-2998.firebaseio.com"
firebaseStorageBucket:      "fiery-inferno-2998.appspot.com"
firebaseMessagingSenderId:  "506104124169"

firebaseLogEntriesRef:      "avenir/log-entries/"

title: Avenir
email:
description:
baseurl: ""
url: ""
twitter_username:
github_username:

# Build settings
markdown: kramdown
